import { defineStore } from 'pinia'
import { reactive } from 'vue'

export const useAppStore = defineStore('store', () => {
  const houses = reactive([
    {
      id: 1,
      name: 'Cozy Cottage',
      price: 250000,
      address: '123 Maple St, Springfield',
      isBookmarked: false,
      rating: 4.2,
      reviewCounts: 15,
      sqft: 1200,
      bedrooms: 2,
      bathrooms: 1,
      facilities: ['car parking', 'wi-fi'],
      gallery: ['https://example.com/house1/img1.jpg', 'https://example.com/house1/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Alice Smith',
          rate: 4,
          reviewDate: '2025-01-10',
          content: 'Lovely place, great location!',
          reviewerPicture: 'https://example.com/reviewer1.jpg',
        },
      ],
    },
    {
      id: 2,
      name: 'Modern Villa',
      price: 450000,
      address: '456 Oak Ave, Rivertown',
      isBookmarked: true,
      rating: 4.8,
      reviewCounts: 22,
      sqft: 2000,
      bedrooms: 4,
      bathrooms: 3,
      facilities: ['car parking', 'swimming', 'gym', 'wi-fi'],
      gallery: ['https://example.com/house2/img1.jpg', 'https://example.com/house2/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Bob Johnson',
          rate: 5,
          reviewDate: '2025-03-15',
          content: 'Amazing amenities!',
          reviewerPicture: 'https://example.com/reviewer2.jpg',
        },
      ],
    },
    {
      id: 3,
      name: 'Urban Loft',
      price: 320000,
      address: '789 Pine Rd, Cityville',
      isBookmarked: false,
      rating: 4.0,
      reviewCounts: 10,
      sqft: 1500,
      bedrooms: 3,
      bathrooms: 2,
      facilities: ['wi-fi', 'restaurant'],
      gallery: ['https://example.com/house3/img1.jpg', 'https://example.com/house3/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Clara Brown',
          rate: 4,
          reviewDate: '2025-02-20',
          content: 'Great for city living.',
          reviewerPicture: 'https://example.com/reviewer3.jpg',
        },
      ],
    },
    {
      id: 4,
      name: 'Family Home',
      price: 380000,
      address: '101 Cedar Ln, Suburbia',
      isBookmarked: true,
      rating: 4.5,
      reviewCounts: 18,
      sqft: 1800,
      bedrooms: 3,
      bathrooms: 2,
      facilities: ['car parking', 'wi-fi'],
      gallery: ['https://example.com/house4/img1.jpg', 'https://example.com/house4/img2.jpg'],
      reviews: [
        {
          reviewerName: 'David Lee',
          rate: 4,
          reviewDate: '2025-04-05',
          content: 'Perfect for families.',
          reviewerPicture: 'https://example.com/reviewer4.jpg',
        },
      ],
    },
    {
      id: 5,
      name: 'Luxury Condo',
      price: 600000,
      address: '202 Birch St, Downtown',
      isBookmarked: false,
      rating: 4.9,
      reviewCounts: 25,
      sqft: 2200,
      bedrooms: 4,
      bathrooms: 3,
      facilities: ['car parking', 'swimming', 'gym', 'restaurant', 'wi-fi'],
      gallery: ['https://example.com/house5/img1.jpg', 'https://example.com/house5/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Emma Wilson',
          rate: 5,
          reviewDate: '2025-05-12',
          content: 'Luxury at its best!',
          reviewerPicture: 'https://example.com/reviewer5.jpg',
        },
      ],
    },
    {
      id: 6,
      name: 'Rustic Retreat',
      price: 200000,
      address: '303 Elm Dr, Countryside',
      isBookmarked: true,
      rating: 4.1,
      reviewCounts: 12,
      sqft: 1000,
      bedrooms: 2,
      bathrooms: 1,
      facilities: ['car parking'],
      gallery: ['https://example.com/house6/img1.jpg', 'https://example.com/house6/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Frank Davis',
          rate: 4,
          reviewDate: '2025-06-01',
          content: 'Peaceful and cozy.',
          reviewerPicture: 'https://example.com/reviewer6.jpg',
        },
      ],
    },
    {
      id: 7,
      name: 'City Apartment',
      price: 280000,
      address: '404 Spruce St, Metropolis',
      isBookmarked: false,
      rating: 3.9,
      reviewCounts: 8,
      sqft: 900,
      bedrooms: 1,
      bathrooms: 1,
      facilities: ['wi-fi', 'restaurant'],
      gallery: ['https://example.com/house7/img1.jpg', 'https://example.com/house7/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Grace Kim',
          rate: 3,
          reviewDate: '2025-07-10',
          content: 'Good for singles.',
          reviewerPicture: 'https://example.com/reviewer7.jpg',
        },
      ],
    },
    {
      id: 8,
      name: 'Suburban Bungalow',
      price: 350000,
      address: '505 Willow Ave, Greenfields',
      isBookmarked: true,
      rating: 4.3,
      reviewCounts: 20,
      sqft: 1600,
      bedrooms: 3,
      bathrooms: 2,
      facilities: ['car parking', 'wi-fi'],
      gallery: ['https://example.com/house8/img1.jpg', 'https://example.com/house8/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Henry Moore',
          rate: 4,
          reviewDate: '2025-08-15',
          content: 'Spacious and modern.',
          reviewerPicture: 'https://example.com/reviewer8.jpg',
        },
      ],
    },
    {
      id: 9,
      name: 'Penthouse Suite',
      price: 750000,
      address: '606 Chestnut Blvd, Uptown',
      isBookmarked: false,
      rating: 4.7,
      reviewCounts: 30,
      sqft: 2500,
      bedrooms: 5,
      bathrooms: 4,
      facilities: ['car parking', 'swimming', 'gym', 'wi-fi'],
      gallery: ['https://example.com/house9/img1.jpg', 'https://example.com/house9/img2.jpg'],
      reviews: [
        {
          reviewerName: 'Isabella Clark',
          rate: 5,
          reviewDate: '2025-09-01',
          content: 'Stunning views!',
          reviewerPicture: 'https://example.com/reviewer9.jpg',
        },
      ],
    },
    {
      id: 10,
      name: 'Country Estate',
      price: 500000,
      address: '707 Laurel Rd, Ruralville',
      isBookmarked: true,
      rating: 4.4,
      reviewCounts: 16,
      sqft: 3000,
      bedrooms: 4,
      bathrooms: 3,
      facilities: ['car parking', 'swimming'],
      gallery: ['https://example.com/house10/img1.jpg', 'https://example.com/house10/img2.jpg'],
      reviews: [
        {
          reviewerName: 'James Taylor',
          rate: 4,
          reviewDate: '2025-09-10',
          content: 'Great for nature lovers.',
          reviewerPicture: 'https://example.com/reviewer10.jpg',
        },
      ],
    },
  ])

  function toggleBookmark(id) {
    houses.map((house) => {
      if (house.id === id) {
        house.isBookmarked = !house.isBookmarked
      }
    })
  }

  return { houses, toggleBookmark }
})
